# on:
#   schedule:
#     - cron:  '30 6 * * 0'

on: workflow_dispatch
name: update keywords
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: setup virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: cache environment
        id: cached-dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
          
      - if: steps.cached-dependencies.outputs.cache-hit != 'true'
        name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-Levenshtein    
 
      - name: execute py script
        run: python trends.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update keywords.json" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}  
